[package]
name = "shepherd"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.27"
env_logger = "0.11"
regex = "1"
clap = { version = "4.0", features = ["derive"] }
tera = "1.19"
dot-parser = "0.3.3"
cached = "0.55.1"

[profile.release]
debug = true
