name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
    - uses: actions/checkout@v2 
    - name: Set up Rust 
      uses: actions-rs/toolchain@v1 
      with: 
        toolchain: stable 
        profile: minimal 
        override: true 
    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
    - name: Build 
      run: cargo build --verbose 
