name: Clippy Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    name: Run Clippy & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: |
          set -x
          cargo clippy -- -D warnings

      - name: Run Tests
        run: |
          set -x
          cargo test --all-features --verbose